image: 'registry.gitlab.com/shardus/dev-container'

before_script:
  - node -v

stages:
  - build

cache:
  paths:
    - node_modules/

# Build Job: Compiles the code
install-job:
  stage: build
  script:
    - echo "Clean install of project dependencies..."
    - npm ci # Clean install of project dependencies
    - echo "Install complete."

# Lint Job: Runs ESLint for code linting
lint-job:
  stage: build
  script:
    - echo "Running ESlint..."
    - npm run lint
    - echo "Running ESlint complete."

# Format Checker Job: Runs a code formatter
format-checker-job:
  stage: build
  script:
    - echo "Running code formatter..."
    - npm run format-check
    - echo "Code formatting complete."
